version: '3.7'
services:
    mysql57:
        image: mysql:5.7
        env_file: [docker.env]
        restart: always

    mysql80:
        image: mysql:8
        env_file: [docker.env]
        restart: always

    postgres95:
        image: postgres:9.5
        env_file: [docker.env]
        restart: always

    postgres13:
        image: postgres:13.1
        env_file: [docker.env]
        restart: always

    php74:
        build:
            context: .
            dockerfile: ./php74/Dockerfile
        restart: "no"
        env_file: [docker.env]
        working_dir: /var/www/html
        volumes:
            - "${APP_DIR}:/var/www/html"

    php80:
        build:
            context: .
            dockerfile: ./php80/Dockerfile
        restart: "no"
        env_file: [docker.env]
        working_dir: /var/www/html
        volumes:
            - "${APP_DIR}:/var/www/html"
